security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
            app_user_providers:
                entity:
                    class: App\Entity\User
                    property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - App\Security\JwtAutenticador
